### ISSUE TITLE
Heat banks and Heat exchangers

### ISSUE THREAD

**Issue by CptMoore** [ACCount12/ExtendedInformation#1]
https://github.com/ACCount12/ExtendedInformation/blob/218092c5d1421edf888e5d9d80aeafb82f4cc033/ExtendedInformation.cs#L213

I believe heat banks and exchangers are not properly managed through that code? (subtype exclusion looks odd, dunnow)

my not so perfect fixes are here
https://github.com/CptMoore/StatsFixMod/blob/master/source/MechStatisticsRulesCalculateHeatEfficiencyStatPatch.cs#L59

I go through all items to search for those stats. I don't know if the core code summarizes first and then does multiplication or does it in order like my code does.

In any case, would be cool to have those data points in the tooltip too.

And btw awesome job, really like it.

**Comment by ACCount12** [comment]
That line was clearly a leftover from copypasting code. Removed it. It should work the same way as your mod now.

**Comment by CptMoore** [comment]
I believe you are right thx
