### ISSUE TITLE
BTStatistics not necessary?

### ISSUE THREAD

**Issue by CptMoore** [ACCount12/ExtendedInformation#2]
https://github.com/ACCount12/ExtendedInformation/blob/218092c5d1421edf888e5d9d80aeafb82f4cc033/ExtendedInformation.cs#L461

I just reuse what is provided in bt
https://github.com/CptMoore/StatsFixMod/blob/master/source/Utils.cs

**Comment by ACCount12** [comment]
I decided that creating and dragging around an entire StatCollection every time a tooltip is drawn wouldn't be wise.

**Comment by CptMoore** [comment]
Easy then
